# Generated by Django 3.2.19 on 2023-06-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0002_auto_20230620_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_api.multiplechoicequestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_api.form'),
        ),
    ]
