# Generated by Django 3.2.19 on 2023-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0003_auto_20230622_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='jurisdiction_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
