# Generated by Django 3.2.19 on 2023-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0004_auto_20231211_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variable_name',
            field=models.CharField(default='Undefined', max_length=50),
            preserve_default=False,
        ),
    ]
