# Generated by Django 3.2.19 on 2023-06-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_months', models.IntegerField()),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_months',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions_api.subscriptionoption'),
        ),
    ]
