# Generated by Django 3.2.19 on 2023-12-09 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdictions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
