# Generated by Django 3.2.19 on 2023-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField()),
                ('stripe_pid', models.CharField(blank=True, max_length=50, null=True)),
                ('client_secret', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('stripe_error', models.CharField(max_length=50)),
                ('requested_subscription_months', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('billing_street_1', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_street_2', models.CharField(blank=True, max_length=50, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('stripe_card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('intended_date', models.DateTimeField()),
                ('completed_or_failed_date', models.DateTimeField()),
            ],
        ),
    ]
