# Generated by Django 3.2.19 on 2023-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
