# Generated by Django 3.2.19 on 2023-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0002_alter_payment_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completed_or_failed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='intended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
