# Generated by Django 3.2.19 on 2023-06-13 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_api', '0003_auto_20230613_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='completed_or_failed_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='intended_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='requested_subscription_months',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_card_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_error',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_street_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_street_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
