# Generated by Django 3.2.19 on 2023-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0006_payment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_street_1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_street_2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='county',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_or_failed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='intended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
