# Generated by Django 3.2.19 on 2023-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0007_auto_20230616_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='requested_subscription_months',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vat',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_option_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
