# Generated by Django 3.2.19 on 2023-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0009_auto_20231211_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
