# Generated by Django 3.2.19 on 2023-06-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ordinal', models.IntegerField()),
                ('explainer', models.CharField(max_length=255)),
                ('variable_name', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rules_api.rule_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RuleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('ordinal', models.IntegerField()),
                ('tier_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlatRateRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_api.rule')),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rules_api.rule',),
        ),
        migrations.CreateModel(
            name='TieredRateRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_api.rule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rules_api.rule',),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_id', models.IntegerField()),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_api.taxcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTieredRateRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_api.rule')),
                ('primary_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_api.tieredraterule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rules_api.rule',),
        ),
        migrations.CreateModel(
            name='SecondaryRuleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('primary_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_api.ruletier')),
                ('secondary_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_api.secondarytieredraterule')),
            ],
        ),
        migrations.AddField(
            model_name='ruletier',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_api.tieredraterule'),
        ),
    ]
