# Generated by Django 3.2.19 on 2023-12-12 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_api', '0003_auto_20231209_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxruletierresult',
            name='taxable_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='taxruletierresult',
            name='variable_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
