# Generated by Django 3.2.19 on 2023-12-15 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_api', '0006_auto_20231215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatraterule',
            name='flat_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rule',
            name='ordinal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ruletier',
            name='min_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
