# Generated by Django 3.2.19 on 2024-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_api', '0007_auto_20231215_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryruletier',
            name='ordinal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
